version: "3.3"

# Build all images:
#
# $ docker-compose -f docker-compose.yml build
#
# Start the development instance:
#
# $ docker-compose -f docker-compose.yml up
#

#volumes:

services:
  cathapi-redis:
    restart: always
    build:
       context: ./redis/
    networks:
      default:
        aliases:
          - cathapi-redis

  cathapi-django:
    restart: always
    build:
      context: ../
      dockerfile: ./Docker/cathapi/Dockerfile
    depends_on:
      - cathapi-redis
    environment:
      - CATHAPI_DEBUG=CONTAINER
    command: /cathapi/entrypoint.sh python3 manage.py runserver
    ports:
      - "8000:8000"

  cathapi-celery:
    restart: always
    build:
      context: ../
      dockerfile: ./Docker/cathapi/Dockerfile
    depends_on:
      - cathapi-redis
    environment:
      - CATHAPI_DEBUG=CONTAINER
    command: celery -A cathapi worker
