version: "3.3"

# Build all images:
#
# $ docker-compose -f docker-compose.yml build
#
# Start the development instance:
#
# $ docker-compose -f docker-compose.yml up
#

#volumes:

services:
  redis:
    restart: always
    build:
       context: ./redis/
    #celery
    #django
