# Generated by Django 2.0.7 on 2018-07-31 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SelectTemplateTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fasta', models.CharField(max_length=2000)),
                ('status', models.CharField(choices=[('unknown', 'unknown'), ('queued', 'queued'), ('running', 'running'), ('error', 'error'), ('success', 'success')], default='initialised', max_length=10)),
                ('message', models.CharField(max_length=150)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('results', models.CharField(blank=True, max_length=5000)),
                ('ip', models.GenericIPAddressField(default='0.0.0.0')),
            ],
        ),
    ]
