# Generated by Django 2.0.7 on 2018-07-31 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selecttemplatetask',
            name='status',
            field=models.CharField(choices=[('Initialised', 'Initialised'), ('Queueing', 'Queueing'), ('Running', 'Running'), ('Completed', 'Completed'), ('Error', 'Error')], default='Initialised', max_length=15),
        ),
    ]
