#!/usr/bin/env python3

"""
CLI tool to search for template structures for modelling 
"""

from cathsm.apiclient import managers

if __name__ == '__main__':
    client = managers.CathSelectTemplateManager.new_from_cli()
    client.run()
