#!/usr/bin/env python3

"""
CLI tool to submit/retrieve models from alignment data
"""

from cathsm.apiclient.managers import SMAlignmentApiClientManager

if __name__ == '__main__':
    client = SMAlignmentApiClientManager.new_from_cli()
    client.run()
