#!/usr/bin/env python3

"""
CLI tool to submit/retrieve models from alignment data
"""

from cathsm.apiclient import managers

if __name__ == '__main__':
    client = managers.SMAlignmentManager.new_from_cli()
    client.run()
